Repository nextcord/nextcord, pull requests merged in 2021-12, with the labels that each got.

#234 Add interaction.send()
  nextcord/interactions.py
Labels: t: enhancement, p: low, s: awaiting review

#211 Add webhook example
  examples/webhook.py
Labels: t: docs, s: awaiting review

#201 Bugfix for task.loop
  nextcord/ext/tasks/__init__.py
Labels: t: bug, p: high, s: awaiting review

#259 Bump aiohttp version
  requirements.txt
Labels: s: stalled
