Repository nextcord/nextcord, pull requests merged in 2021-11, with the labels that each got.

#245 Changed Capitalization to be better(On README)
  README.rst
Labels: t: docs, p: low, s: awaiting review

#255 Adding 3.10 in supported python versions
  setup.py
  unaliased-setup.py
Labels: s: stalled, p: high, t: meta

#273 Fix embed.url description.
  nextcord/embeds.py
Labels: t: docs, p: low, s: awaiting review

#233 Feature: Cog's can now have external config
  docs/ext/commands/api.rst
  nextcord/ext/commands/bot.py
  nextcord/ext/commands/errors.py
Labels: t: enhancement, p: low, s: awaiting review

#238 Feature: Group's hook & check inheritance
  nextcord/ext/commands/core.py
Labels: t: enhancement, s: awaiting review
