Repository nextcord/nextcord, pull requests merged in 2022-03, with the labels that each got.

#445 Adding modals
  docs/api.rst
  examples/modals/modal.py
  examples/modals/persistent.py
  nextcord/client.py
  nextcord/components.py
  nextcord/enums.py
  nextcord/interactions.py
  nextcord/state.py
  nextcord/types/components.py
  nextcord/ui/__init__.py
  nextcord/ui/modal.py
  nextcord/ui/text_input.py
  nextcord/ui/view.py
Labels: t: enhancement, p: medium, s: awaiting review

#515 Fix audio delay when calling after function
  nextcord/player.py
Labels: t: bug, p: low, s: awaiting review

#348 slash checks/hooks
  discord/application_command.py
  docs/api.rst
  docs/conf.py
  docs/ext/application_checks/index.rst
  docs/index.rst
  nextcord/application_command.py
  nextcord/client.py
  nextcord/errors.py
  nextcord/ext/application_checks/__init__.py
  nextcord/ext/application_checks/core.py
  nextcord/ext/application_checks/errors.py
  nextcord/ext/commands/bot.py
  nextcord/ext/commands/cog.py
  nextcord/interactions.py
  nextcord/state.py
  nextcord/types/checks.py
  setup.py
Labels: t: enhancement, p: medium, s: awaiting review

#517 Cython compatibility
  docs/extensions/attributetable.py
  nextcord/ext/commands/cog.py
  nextcord/ext/commands/core.py
  nextcord/ext/tasks/__init__.py
  nextcord/member.py
  nextcord/ui/button.py
  nextcord/ui/select.py
Labels: t: bug, s: in progress, p: medium

#536 feat: asynchronousifying setup function in cogs
  docs/ext/commands/extensions.rst
  docs/faq.rst
  nextcord/ext/commands/bot.py
Labels: t: enhancement, s: in progress, p: low
