Repository nextcord/nextcord, pull requests merged in 2022-09, with the labels that each got.

#791 feat(app-cmds): add get_mention to Slash Commands
  nextcord/application_command.py
Labels: t: enhancement, p: low, s: awaiting review, 2.2

#787 docs(examples): add a localization example
  examples/application_commands/localization.py
Labels: t: docs, p: low, s: awaiting review

#766 feat(app-cmds): support Range/String for min/max value/length options
  docs/api.rst
  nextcord/application_command.py
Labels: t: enhancement, p: low, s: awaiting review, 2.2

#804 docs(examples): fix example not using defined intents
  examples/custom_context.py
Labels: t: docs, p: medium

#803 feat: add the ability to use custom interactions
  examples/custom_interaction.py
  nextcord/client.py
  nextcord/state.py
Labels: p: low, s: awaiting review, 2.2

#792 fix(app-cmds): delete_application_commands for guild commands
  nextcord/client.py
  nextcord/state.py
Labels: t: bug, p: medium, 2.2

#809 refactor(enums)!: remove TriggerType.harmful_link
  docs/api.rst
  nextcord/enums.py
Labels: p: medium, s: awaiting review, t: removal, 2.2

#806 fix(ui): View.add_item is partially unknown
  nextcord/ui/view.py
Labels: t: bug, p: medium, s: awaiting review, 2.3

#773 feat: support resume_gateway_url for resuming
  nextcord/client.py
  nextcord/gateway.py
  nextcord/http.py
Labels: p: high, s: awaiting review, t: api coverage, 2.3

#813 feat: use delete_message_seconds for Guild/Member.ban
  nextcord/guild.py
  nextcord/http.py
  nextcord/member.py
Labels: p: medium, t: api coverage, 2.3
