Repository nextcord/nextcord, pull requests merged in 2022-11, with the labels that each got.

#878 fix(abc): move import from TYPE_CHECKING to runtime
  nextcord/abc.py
Labels: t: bug, p: high, 2.3

#736 feat(app-cmds): give descriptive error message when params are missing
  nextcord/application_command.py
Labels: t: enhancement, s: in progress, p: low

#876 build: use aiohttp[speedups] so cchardet isnt installed >=3.10
  setup.py
Labels: t: bug, p: high, s: awaiting review

#881 fix(app-cmds): typing module is not imported
  nextcord/application_command.py
Labels: t: bug, p: high

#877 refactor: correctly type utils
  discord/activity.py
  discord/integrations.py
  discord/invite.py
  discord/role.py
  discord/template.py
  discord/threads.py
  discord/utils.py
  discord/welcome_screen.py
  discord/widget.py
  nextcord/activity.py
  nextcord/audit_logs.py
  nextcord/auto_moderation.py
  nextcord/channel.py
  nextcord/client.py
  nextcord/ext/commands/converter.py
  nextcord/ext/commands/help.py
  nextcord/gateway.py
  nextcord/guild.py
  nextcord/http.py
  nextcord/integrations.py
  nextcord/interactions.py
  nextcord/invite.py
  nextcord/member.py
  nextcord/message.py
  nextcord/partial_emoji.py
  nextcord/role.py
  nextcord/scheduled_events.py
  nextcord/state.py
  nextcord/team.py
  nextcord/template.py
  nextcord/threads.py
  nextcord/user.py
  nextcord/utils.py
  nextcord/webhook/async_.py
  nextcord/webhook/sync.py
  nextcord/widget.py
Labels: p: low, s: awaiting review, t: typing

#880 refactor(ui): improve public annotations
  nextcord/components.py
  nextcord/ui/button.py
  nextcord/ui/item.py
  nextcord/ui/modal.py
  nextcord/ui/select.py
  nextcord/ui/text_input.py
  nextcord/ui/view.py
Labels: p: low, s: awaiting review, t: typing

#873 feat(audit-logs): `auto_moderation_flag_to_channel`, `auto_moderation_user_communication_disabled` types
  docs/api.rst
  nextcord/audit_logs.py
  nextcord/enums.py
Labels: p: medium, s: awaiting review, t: api coverage, 2.3

#838 feat: default_sort_order
  docs/api.rst
  nextcord/abc.py
  nextcord/channel.py
  nextcord/enums.py
  nextcord/guild.py
  nextcord/http.py
  nextcord/types/channel.py
Labels: p: medium, s: awaiting review, t: api coverage, 2.3

#837 feat: mention total limit
  docs/api.rst
  nextcord/auto_moderation.py
  nextcord/enums.py
  nextcord/types/auto_moderation.py
Labels: p: medium, s: awaiting review, t: api coverage, 2.3

#888 fix: Unable to import nextcord.types.checks
  nextcord/types/checks.py
Labels: t: bug, p: high, s: awaiting review

#833 feat(app-cmds): default_guild_ids
  docs/interactions.rst
  nextcord/application_command.py
  nextcord/client.py
  nextcord/ext/commands/bot.py
  nextcord/shard.py
Labels: t: enhancement, p: low, s: awaiting review, 2.3

#893 ci: remove pre-commit
  .github/workflows/lint.yml
Labels: p: medium, t: meta

#900 docs(ui): fix *SelectValues
  docs/api.rst
  nextcord/ui/select/channel.py
  nextcord/ui/select/mentionable.py
  nextcord/ui/select/role.py
  nextcord/ui/select/user.py
Labels: t: bug, p: critical

#901 fix(app-cmds): issubclass check failed w/ normal objects
  nextcord/application_command.py
Labels: t: bug, p: critical, s: awaiting review

#897 feat(flags): add `ACTIVE_APPLICATION` & `ACTIVE_DEVELOPER` flags
  docs/api.rst
  nextcord/enums.py
  nextcord/flags.py
Labels: p: medium, s: awaiting review, t: api coverage, 2.4

#896 refactor(app-checks): correctly type ApplicationCheckAnyFailure
  nextcord/ext/application_checks/errors.py
Labels: p: low, s: awaiting review, t: typing

#895 refactor: use explicit union[str, int] with *HasRole errors
  nextcord/ext/application_checks/errors.py
  nextcord/ext/commands/errors.py
Labels: p: low, s: awaiting review, t: typing

#904 docs(contributing): add more info to the guide
  .github/CONTRIBUTING.md
  CONTRIBUTING.md
  requirements-dev.txt
Labels: t: docs, p: low, s: awaiting review

#869 typing(abc): type set_permissions parameters
  nextcord/abc.py
Labels: p: low, s: awaiting review, t: typing

#868 ci: add support for linting Python 3.11
  .github/workflows/lint.yml
  pyproject.toml
  setup.py
  unaliased-setup.py
Labels: p: medium, t: meta, s: awaiting review

#889 fix: last_message_id not updating on VoiceChannel
  nextcord/state.py
Labels: t: bug, p: medium, s: awaiting review

#909 fix(app-cmds): Fix optional params causing error when lazy loading.
  nextcord/application_command.py
Labels: t: bug, p: high, s: awaiting review

#911 refactor(enums): use bitshifting for bitwise enums
  nextcord/enums.py
Labels: p: low, t: refactor

#912 feat(enums): HTTP interaction bot flag
  docs/api.rst
  nextcord/enums.py
Labels: p: low, s: awaiting review, t: api coverage

#920 fix(select-channel): import GuildChannel at runtime
  nextcord/ui/select/channel.py
Labels: t: bug, p: high, s: awaiting review

#872 typing(iterators): correctly typehint iterators
  nextcord/iterators.py
Labels: p: medium, s: awaiting review, t: typing
