Repository nextcord/nextcord, pull requests merged in 2022-07, with the labels that each got.

#721 feat(interactions): add the app_permissions field
  nextcord/interactions.py
  nextcord/types/interactions.py
Labels: t: enhancement, p: medium, s: awaiting review, 2.1

#723 docs: Fix docstring return type of app_permissions
  nextcord/interactions.py
Labels: t: docs, p: low, s: awaiting review, 2.1

#726 fix(ui): Modal & View dispatch orders
  nextcord/ui/modal.py
  nextcord/ui/view.py
Labels: t: bug, p: medium, s: awaiting review, 2.1

#725 docs(channel): fix VoiceChannel docstrings
  nextcord/channel.py
Labels: t: docs, p: medium, s: awaiting review, 2.1

#719 refactor(bot)!: remove the use of **options for options
  nextcord/application_command.py
  nextcord/ext/commands/bot.py
  nextcord/ext/commands/core.py
  nextcord/utils.py
Labels: p: high, s: awaiting review, 2.1, t: refactor

#714 feat(message): add Message.interaction
  docs/api.rst
  nextcord/message.py
  nextcord/types/interactions.py
Labels: t: enhancement, p: low, s: awaiting review, 2.1

#692 docs(examples): Add select example in modal
  examples/modals/modal.py
Labels: t: docs, p: low, s: awaiting review, 2.1

#727 docs(assets): July themed server assets
  assets/server-banner-july.png
  assets/server-icon-july.jpg
Labels: t: meta, s: awaiting review

#733 feat(ClientCog): remove ClientCog.to_register
  nextcord/application_command.py
Labels: p: medium, 2.1, t: removal

#734 fix(commands): help commands not getting added
  nextcord/ext/commands/bot.py
Labels: t: bug, p: high, s: awaiting review, 2.1

#732 feat(app-cmds): support min/max length for string options
  nextcord/application_command.py
  nextcord/types/interactions.py
Labels: t: enhancement, p: low, s: awaiting review, 2.1

#724 fix(interactions): get info from cache first if available
  nextcord/interactions.py
Labels: t: bug, p: low, s: awaiting review, 2.1

#741 fix(audit-logs): audit logs after strategy
  nextcord/http.py
  nextcord/iterators.py
Labels: t: bug, p: high, s: awaiting review, 2.1

#739 feat(interactions): add Interaction hash + fix PartialInteractionMessage hash
  nextcord/interactions.py
Labels: t: bug, p: low, s: awaiting review, 2.1

#738 docs(version_guarantees): add minor may break
  docs/version_guarantees.rst
Labels: t: docs, s: awaiting review

#598 feat(commands): add bot.load_extensions
  nextcord/ext/commands/bot.py
Labels: t: enhancement, p: low, s: awaiting review

#735 fix(commands): use AutoShardedClient initialiser
  nextcord/ext/commands/bot.py
Labels: t: bug, p: high, s: awaiting review, 2.1

#746 docs(examples): add message_content or remove prefix where applicable
  examples/application_commands/autocompleted_command.py
  examples/application_commands/choices.py
  examples/application_commands/context_menus.py
  examples/application_commands/slash_command.py
  examples/application_commands/sub_commands.py
  examples/background_task.py
  examples/background_task_asyncio.py
  examples/basic_bot.py
  examples/basic_voice.py
  examples/converters.py
  examples/custom_context.py
  examples/deleted.py
  examples/edits.py
  examples/guessing_game.py
  examples/head_or_tails.py
  examples/modals/modal.py
  examples/modals/persistent.py
  examples/new_member.py
  examples/reaction_roles.py
  examples/reply.py
  examples/secret.py
  examples/secure_token_storage.py
  examples/views/confirm.py
  examples/views/counter.py
  examples/views/dropdown.py
  examples/views/ephemeral.py
  examples/views/link.py
  examples/views/persistent.py
  examples/views/tic_tac_toe.py
Labels: t: docs, p: low, s: awaiting review

#743 fix(commands): resolve unexpected kwarg errors with GroupMixin
  nextcord/ext/commands/core.py
Labels: t: bug, p: high, s: awaiting review, 2.1

#750 feat(flags): add ApplicationFlags.application_command_badge
  nextcord/flags.py
Labels: t: enhancement, p: medium, s: awaiting review, 2.1

#656 chore(readme): add an example slash command
  README.rst
Labels: p: low, t: meta, s: awaiting review

#607 feat: support more input types where files are used
  nextcord/channel.py
  nextcord/client.py
  nextcord/guild.py
  nextcord/http.py
  nextcord/role.py
  nextcord/scheduled_events.py
  nextcord/template.py
  nextcord/user.py
  nextcord/utils.py
  nextcord/webhook/async_.py
  nextcord/webhook/sync.py
Labels: t: enhancement, p: low, s: awaiting review

#742 feat(app-cmds): add qualified_name
  nextcord/application_command.py
Labels: t: enhancement, p: low, s: awaiting review, 2.1

#740 feat: add auto moderation support
  docs/api.rst
  nextcord/__init__.py
  nextcord/audit_logs.py
  nextcord/auto_moderation.py
  nextcord/enums.py
  nextcord/flags.py
  nextcord/guild.py
  nextcord/http.py
  nextcord/iterators.py
  nextcord/state.py
  nextcord/types/audit_log.py
  nextcord/types/auto_moderation.py
  nextcord/types/guild.py
Labels: t: enhancement, p: medium, s: awaiting review, 2.1
