Repository nextcord/nextcord, pull requests merged in 2022-12, with the labels that each got.

#925 fix(iterators): switch _MappedAsyncIterator inheritance order
  nextcord/iterators.py
Labels: t: bug, p: high, s: awaiting review

#926 fix(commands): stop setting private attribute directly
  nextcord/ext/commands/core.py
Labels: t: bug, p: critical, s: awaiting review

#943 feat(enums): add indonesian locale
  nextcord/enums.py
Labels: p: medium, t: api coverage, s: waiting for discord

#948 fix(ui.select): type checking imports used at runtime
  nextcord/ui/select/mentionable.py
  nextcord/ui/select/role.py
Labels: t: bug, p: high, s: awaiting review

#944 docs(flags): reword docs for `discord_certified_moderator`
  nextcord/flags.py
Labels: t: docs, p: medium, s: awaiting review

#907 refactor(mentions): use None instead of _FakeBool
  nextcord/mentions.py
Labels: p: low, s: awaiting review, t: refactor
