Repository nextcord/nextcord, pull requests merged in 2022-06, with the labels that each got.

#644 fix(scheduled-event-iterator): resolve infinite loop
  nextcord/http.py
  nextcord/iterators.py
  nextcord/scheduled_events.py
Labels: t: bug, p: medium, s: awaiting review

#649 fix: guild iterator pagination + limits
  nextcord/client.py
  nextcord/iterators.py
Labels: t: bug, p: high, s: awaiting review

#657 Added ignore_forbidden kwarg to sync_all_application_commands, fixed …
  nextcord/application_command.py
  nextcord/client.py
  nextcord/state.py
Labels: t: bug, p: high, s: awaiting review

#661 Fixes gateway voice hook fallback
  nextcord/gateway.py
Labels: t: bug, p: high, s: awaiting review

#659 docs: add punctuation & grammar
  docs/discord.rst
  docs/faq.rst
  docs/images/discord_create_app_button.png
  docs/images/discord_create_app_form.png
  docs/images/discord_create_bot_user.png
  docs/index.rst
  docs/intents.rst
  docs/interactions.rst
  docs/intro.rst
  docs/logging.rst
  docs/migrating.rst
  docs/migrating_2.rst
  docs/migrating_to_async.rst
  docs/migrating_to_nextcord.rst
  docs/quickstart.rst
  docs/requirements.txt
  docs/version_guarantees.rst
  docs/whats_new.rst
Labels: t: docs, p: low, s: awaiting review

#664 fix(app-cmds): dm_permission causing resync and cmds via bot not registering fully
  nextcord/application_command.py
  nextcord/client.py
Labels: t: bug, p: high, s: awaiting review

#670 feat(guild): update `Guild.stickers_limit` to match the default limit of 5
  nextcord/guild.py
Labels: t: enhancement, p: low, s: awaiting review

#666 fix(app-checks): fix typing for bot_has[_any]_role to allow str
  nextcord/ext/application_checks/core.py
Labels: p: medium, s: awaiting review, t: typing

#681 fix(interactions): resolve ephemeral channels from cache
  nextcord/state.py
Labels: t: bug, p: medium, s: awaiting review

#684 fix(commands): only set flag annotation if not set yet
  nextcord/ext/commands/flags.py
Labels: t: bug, p: low, s: awaiting review

#662 fix(app-checks): change type aliases to allow for normal funcs
  nextcord/ext/application_checks/core.py
  nextcord/types/checks.py
Labels: p: medium, s: awaiting review, t: typing

#671 feat: Warn when using ext.commands without message content intent
  docs/ext/commands/api.rst
  nextcord/ext/commands/bot.py
Labels: t: enhancement, p: medium, s: awaiting review, 2.0

#683 docs(ui): document public attributes
  nextcord/ui/modal.py
  nextcord/ui/view.py
Labels: t: docs, p: low, s: awaiting review

#669 feat: refactor modals to fix select menus
  nextcord/types/components.py
  nextcord/types/interactions.py
  nextcord/ui/item.py
  nextcord/ui/modal.py
  nextcord/ui/select.py
  nextcord/ui/text_input.py
  nextcord/ui/view.py
Labels: t: enhancement, p: medium, s: awaiting review, 2.0

#687 refactor(gateway): remove the `$` prefix
  nextcord/gateway.py
Labels: p: low, s: awaiting review

#617 chore: add tag-epic to license headers
  nextcord/raw_models.py
  nextcord/threads.py
  nextcord/types/channel.py
  nextcord/types/components.py
  nextcord/widget.py
Labels: p: low, t: meta, s: awaiting review

#643 refactor: lint and edit examples folder
  examples/application_commands/slash_command.py
  examples/basic_bot.py
  examples/converters.py
  examples/guessing_game.py
  examples/secret.py
  examples/views/counter.py
  examples/views/ephemeral.py
Labels: t: docs, p: low, s: awaiting review

#688 ci(docs): update checkout and setup-python
  .github/workflows/docs.yml
Labels: p: low, t: meta, s: awaiting review

#685 fix(ext-cmds): copy context before dispatching on_command
  nextcord/ext/commands/bot.py
Labels: t: bug, p: low, s: awaiting review, 2.0

#698 fix: Apply checks to context menu commands
  nextcord/application_command.py
Labels: t: bug, p: medium, s: awaiting review, 2.0

#693 ci(publish): update tool versions
  .github/workflows/publish.yml
Labels: p: low, t: meta, s: awaiting review

#689 docs: Make Guild invite documentation clearer regarding Vanity invites
  nextcord/guild.py
Labels: t: docs, p: low, s: awaiting review

#703 docs(migrating): fix broken link and reword "info"
  docs/migrating_2.rst
Labels: t: docs, p: medium, s: awaiting review

#705 chore: fix incorrect type ignore comments
  nextcord/ext/commands/converter.py
Labels: p: low, s: awaiting review, t: refactor

#712 docs: Add missing TextInput to Item docstring
  nextcord/ui/item.py
Labels: t: docs, p: medium, s: awaiting review

#713 docs: fixes several warnings in the docs
  docs/conf.py
  docs/migrating_2.rst
  nextcord/client.py
  nextcord/ext/commands/bot.py
  nextcord/message.py
  nextcord/widget.py
Labels: t: docs, p: medium, s: awaiting review

#686 feat: add on_application_command_completion event
  docs/ext/application_checks/index.rst
  nextcord/application_command.py
Labels: t: enhancement, p: low, s: awaiting review, 2.1

#716 ci: prevent workflows from running twice
  .github/workflows/docs.yml
  .github/workflows/lint.yml
Labels: t: meta, s: awaiting review

#711 fix: Support unicode emojis in PartialEmojiConverter
  nextcord/ext/commands/converter.py
Labels: t: bug, p: medium, s: awaiting review, 2.1

#699 feat(commands): CommandNotFound now has command_name shortcut to ctx.invoked_with
  nextcord/ext/commands/bot.py
  nextcord/ext/commands/errors.py
Labels: t: enhancement, p: low, s: awaiting review, 2.1
