Repository nextcord/nextcord, pull requests merged in 2022-01, with the labels that each got.

#272 Feat/scheduled events
  .github/CODEOWNERS
  docs/api.rst
  docs/ext/commands/api.rst
  nextcord/__init__.py
  nextcord/audit_logs.py
  nextcord/client.py
  nextcord/enums.py
  nextcord/ext/commands/__init__.py
  nextcord/ext/commands/converter.py
  nextcord/ext/commands/errors.py
  nextcord/flags.py
  nextcord/guild.py
  nextcord/http.py
  nextcord/iterators.py
  nextcord/permissions.py
  nextcord/scheduled_events.py
  nextcord/state.py
  nextcord/types/__init__.py
  nextcord/types/audit_log.py
  nextcord/types/guild.py
  nextcord/types/scheduled_events.py
Labels: t: enhancement, p: medium, s: awaiting review

#235 Feat: Add 'thread' field to messages.
  nextcord/message.py
Labels: t: enhancement, s: awaiting review

#195 Addition of role icons
  nextcord/guild.py
  nextcord/http.py
  nextcord/role.py
  nextcord/types/role.py
Labels: t: enhancement, s: awaiting review

#298 Merge: #298
  .gitignore
  nextcord/interactions.py
  nextcord/types/interactions.py
Labels: t: enhancement, p: medium, s: awaiting review

#318 Add possibility to edit files on a message
  nextcord/http.py
  nextcord/message.py
Labels: t: enhancement, p: medium, s: awaiting review

#358 Add client to interaction class
  nextcord/interactions.py
Labels: t: enhancement

#309 Application Commands Documentation
  docs/api.rst
  docs/index.rst
  docs/interactions.rst
  docs/migrating_2.rst
  docs/migrating_to_nextcord.rst
  examples/application_commands/autocompleted_command.py
  examples/application_commands/choices.py
  examples/application_commands/cog_example.py
  examples/application_commands/context_menus.py
  examples/application_commands/slash_basic.py
  examples/application_commands/slash_command.py
  examples/application_commands/sub_commands.py
Labels: t: docs, s: in progress, p: medium
