Repository nextcord/nextcord, pull requests merged in 2022-10, with the labels that each got.

#822 chore: add missing py.typed meta files
  nextcord/ext/application_checks/py.typed
  nextcord/ext/commands/py.typed
  nextcord/ext/slash_utils/py.typed
  nextcord/ext/tasks/py.typed
Labels: p: medium, t: meta, s: awaiting review

#700 refactor(types): use NotRequired for optional fields
  nextcord/types/__init__.py
  nextcord/types/activity.py
  nextcord/types/appinfo.py
  nextcord/types/audit_log.py
  nextcord/types/auto_moderation.py
  nextcord/types/channel.py
  nextcord/types/checks.py
  nextcord/types/components.py
  nextcord/types/embed.py
  nextcord/types/emoji.py
  nextcord/types/gateway.py
  nextcord/types/guild.py
  nextcord/types/integration.py
  nextcord/types/interactions.py
  nextcord/types/invite.py
  nextcord/types/member.py
  nextcord/types/message.py
  nextcord/types/raw_models.py
  nextcord/types/role.py
  nextcord/types/snowflake.py
  nextcord/types/sticker.py
  nextcord/types/team.py
  nextcord/types/template.py
  nextcord/types/threads.py
  nextcord/types/user.py
  nextcord/types/voice.py
  nextcord/types/webhook.py
  nextcord/types/welcome_screen.py
  nextcord/types/widget.py
Labels: p: low, s: awaiting review, t: refactor

#812 fix(app-cmds): two application commands with the same signatures could be registered
  nextcord/client.py
Labels: t: bug, 2.3

#801 feat: Make enums comparable and hashable as a str or int
  discord/enums.py
  nextcord/enums.py
  nextcord/ext/commands/cooldowns.py
Labels: t: enhancement, p: low, 2.3

#827 docs: lock sphinx and fix toctree
  docs/conf.py
  setup.py
Labels: t: docs, p: medium, s: awaiting review, 2.3

#832 docs(assets): Halloween 2022 server assets
  assets/server-banner-halloween-2022.png
  assets/server-icon-halloween-2022.png
Labels: t: meta

#829 fix(channel): import channel types at runtime
  nextcord/guild.py
Labels: t: bug, p: high, s: awaiting review, 2.3

#826 docs(commands): document cog_command_error is for prefix
  nextcord/ext/commands/cog.py
Labels: t: docs, s: awaiting review

#831 fix(enums): resolve less than or equal comparison
  nextcord/enums.py
Labels: t: bug, p: medium, s: awaiting review

#835 fix(app-cmds): temporarily fix autocomplete integer conversion
  nextcord/application_command.py
Labels: t: bug, p: high, s: awaiting review, 2.3

#850 docs(abc): list ForumChannel as an implementation of GuildChannel
  nextcord/abc.py
Labels: t: docs, p: low, s: awaiting review, hacktoberfest

#830 refactor(gateway): add type annotations
  nextcord/gateway.py
Labels: p: low, s: awaiting review, t: refactor

#805 fix: Messageable.send is partially unknown
  nextcord/abc.py
  nextcord/http.py
Labels: t: bug, s: in progress, p: medium

#851 docs(app-cmds): document SlashCommandMixin.children
  nextcord/application_command.py
Labels: t: docs, p: medium

#854 docs(client): fix nextcord.new mistake
  nextcord/client.py
Labels: t: docs, p: medium

#820 feat(client): add Client.remove_view and Client.remove_modal
  nextcord/client.py
  nextcord/state.py
  nextcord/ui/view.py
Labels: t: enhancement, p: low, s: awaiting review, 2.3

#859 chore: Add removal of unused imports to pre-commit
  .pre-commit-config.yaml
  docs/extensions/exception_hierarchy.py
  nextcord/application_command.py
  nextcord/client.py
  nextcord/ext/application_checks/core.py
  nextcord/ext/application_checks/errors.py
  nextcord/ext/commands/bot.py
  nextcord/ext/commands/cog.py
  nextcord/ext/commands/context.py
  nextcord/gateway.py
  nextcord/http.py
  nextcord/iterators.py
  nextcord/member.py
  nextcord/shard.py
  nextcord/state.py
  nextcord/template.py
  nextcord/webhook/sync.py
Labels: p: low, t: meta, s: awaiting review, t: refactor

#860 docs: Fix version directives in documentation
  nextcord/application_command.py
  nextcord/guild.py
Labels: t: docs, p: low, s: awaiting review

#857 fix(app-cmds): Resolve error with integer conversion in slash commands
  nextcord/application_command.py
Labels: t: bug, p: high, s: awaiting review, 2.3

#855 docs(guild): add DEVELOPER_SUPPORT_SERVER feature
  nextcord/guild.py
  nextcord/types/guild.py
Labels: t: docs, p: low

#862 docs(app-cmds): document on_autocomplete decorator
  nextcord/application_command.py
Labels: t: docs, p: low, s: awaiting review

#864 refactor: Remove duplicate imports and f-strings with no placeholders
  nextcord/application_command.py
  nextcord/client.py
  nextcord/ext/commands/bot.py
  nextcord/http.py
  nextcord/interactions.py
  nextcord/iterators.py
  nextcord/member.py
  nextcord/shard.py
  nextcord/state.py
Labels: p: low, s: awaiting review, t: refactor

#858 fix(abc): handle timeouts in GuildChannel.permissions_for
  nextcord/abc.py
Labels: t: bug, p: medium, s: awaiting review, 2.3

#863 docs: Fix single-backtick words to double-backtick or links
  docs/ext/commands/commands.rst
  docs/whats_new.rst
  nextcord/abc.py
  nextcord/application_command.py
  nextcord/auto_moderation.py
  nextcord/channel.py
  nextcord/client.py
  nextcord/embeds.py
  nextcord/ext/application_checks/core.py
  nextcord/ext/commands/bot.py
  nextcord/ext/commands/converter.py
  nextcord/ext/commands/core.py
  nextcord/ext/tasks/__init__.py
  nextcord/guild.py
  nextcord/invite.py
  nextcord/iterators.py
  nextcord/raw_models.py
  nextcord/state.py
  nextcord/threads.py
  nextcord/utils.py
  nextcord/widget.py
Labels: t: docs, p: low, s: awaiting review

#867 fix: Python3.11 dataclass changes
  nextcord/utils.py
Labels: t: bug, p: high, 2.3

#870 refactor(guild): use Optional for limit kwargs
  nextcord/guild.py
Labels: p: low, s: awaiting review, t: typing

#871 docs(app-cmds): Document .checks, OptionConverter, Commands
  nextcord/application_command.py
Labels: t: docs, p: low

#853 feat(app-cmds): add support for 3.10 unions
  nextcord/application_command.py
Labels: t: enhancement, p: medium, s: awaiting review, 2.3
