Repository nextcord/nextcord, pull requests merged in 2022-04, with the labels that each got.

#383 Pass default_permission correctly (Closes: #373)
  nextcord/application_command.py
  nextcord/client.py
Labels: t: bug, p: medium

#596 feat: add workflows and checks
  .github/CODEOWNERS
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/format.yml
  .github/workflows/lint.yml
  .gitignore
  .pre-commit-config.yaml
  pyproject.toml
  requirements-dev.txt
Labels: t: meta, s: awaiting review

#599 docs: Document migration change to intents
  docs/intents.rst
  docs/migrating_2.rst
  nextcord/appinfo.py
  nextcord/flags.py
Labels: t: docs, p: medium, s: awaiting review, 2.0

#613 fix(Member): add tag-epic to license headers
  nextcord/member.py
Labels: p: low, t: meta, s: awaiting review

#606 feat: fix type issues for the whole library
  nextcord/__main__.py
  nextcord/abc.py
  nextcord/activity.py
  nextcord/asset.py
  nextcord/audit_logs.py
  nextcord/backoff.py
  nextcord/channel.py
  nextcord/client.py
  nextcord/components.py
  nextcord/embeds.py
  nextcord/emoji.py
  nextcord/enums.py
  nextcord/ext/application_checks/core.py
  nextcord/ext/commands/bot.py
  nextcord/ext/commands/cog.py
  nextcord/ext/commands/converter.py
  nextcord/ext/commands/core.py
  nextcord/ext/commands/flags.py
  nextcord/ext/commands/help.py
  nextcord/flags.py
  nextcord/gateway.py
  nextcord/guild.py
  nextcord/http.py
  nextcord/interactions.py
  nextcord/invite.py
  nextcord/iterators.py
  nextcord/member.py
  nextcord/mentions.py
  nextcord/message.py
  nextcord/opus.py
  nextcord/player.py
  nextcord/raw_models.py
  nextcord/scheduled_events.py
  nextcord/shard.py
  nextcord/state.py
  nextcord/team.py
  nextcord/types/invite.py
  nextcord/types/scheduled_events.py
  nextcord/types/template.py
  nextcord/ui/modal.py
  nextcord/ui/text_input.py
  nextcord/ui/view.py
  nextcord/user.py
  nextcord/utils.py
  nextcord/voice_client.py
  nextcord/webhook/async_.py
  nextcord/widget.py
  pyproject.toml
Labels: p: low, s: awaiting review, t: typing

#616 Updated "Creating a Bot Account" Docs
  docs/discord.rst
  docs/images/discord_bot_copy_token.png
  docs/images/discord_bot_user_options.png
  docs/images/discord_oauth2_scope.png
Labels: t: docs, s: awaiting review

#623 refactor: add specific return types for component payloads
  nextcord/ui/button.py
  nextcord/ui/item.py
  nextcord/ui/modal.py
  nextcord/ui/text_input.py
  nextcord/ui/view.py
Labels: p: low, s: awaiting review, t: typing

#626 feat(Embed): return the new embed at `Embed.clear_fields()`
  nextcord/embeds.py
Labels: t: enhancement, p: low, s: awaiting review
