Repository nextcord/nextcord, pull requests merged in 2022-08, with the labels that each got.

#678 feat(app-cmds): channel, Annotated and Literal annotations
  .github/workflows/docs.yml
  docs/api.rst
  docs/requirements.txt
  nextcord/application_command.py
  requirements.txt
  setup.py
Labels: t: enhancement, p: medium, s: awaiting review, 2.1

#760 feat(interactions): make Interaction generic on Client
  nextcord/application_command.py
  nextcord/ext/application_checks/core.py
  nextcord/interactions.py
Labels: t: enhancement, p: low, 2.2

#752 feat: add File.force_close to close bytesio files
  nextcord/asset.py
  nextcord/file.py
  nextcord/message.py
Labels: t: enhancement, p: low, 2.2

#759 docs: bump sphinx requirement
  setup.py
Labels: t: docs, p: medium, s: awaiting review

#764 docs: fix warnings
  docs/conf.py
  nextcord/guild.py
Labels: t: docs, p: low, s: awaiting review

#763 feat(enums): add ChannelType.guild_directory
  docs/api.rst
  nextcord/enums.py
Labels: p: medium, s: awaiting review, 2.2, t: api coverage

#774 docs(api): move float near to other python types
  docs/api.rst
Labels: t: docs, p: low

#780 revert: Add select example in modal
  examples/modals/modal.py
Labels: t: docs, p: medium, s: awaiting review

#753 refactor(embeds): deprecate Embed.Empty in favour of None
  nextcord/embeds.py
Labels: p: low, s: awaiting review, t: refactor, 2.2

#793 fix(message): initialization failing with threads and no intents
  nextcord/message.py
Labels: t: bug, p: medium, s: awaiting review, 2.2

#794 refactor(member): remove deprecated nickname mention syntax
  nextcord/member.py
Labels: p: low, s: awaiting review, t: removal, 2.2

#785 fix(app-cmds): stop syncing on no options/channel type sorting
  nextcord/application_command.py
Labels: t: bug, p: medium, 2.2

#796 fix: Empty lists not sent in payload when files sent
  nextcord/http.py
Labels: t: bug, p: high, s: awaiting review, 2.2

#790 feat: Add Client.parse_mentions, Guild.parse_mentions, Guild.parse_role_mentions, Guild.parse_channel_mentions
  discord/utils.py
  docs/api.rst
  nextcord/client.py
  nextcord/guild.py
  nextcord/message.py
  nextcord/utils.py
Labels: t: enhancement, p: low, s: awaiting review

#797 refactor: Minor refactoring of http.py
  nextcord/http.py
Labels: p: low, s: awaiting review, t: refactor
