Repository nextcord/nextcord, pull requests merged in 2022-05, with the labels that each got.

#630 Return Embed from `Embed.remove_field`
  nextcord/embeds.py
Labels: t: enhancement, p: low, s: awaiting review

#637 Added Member.disconnect function - fixes #636
  nextcord/member.py
Labels: t: enhancement, p: low, s: awaiting review

#652 fix: getting guild when no channel type
  nextcord/message.py
Labels: t: bug, p: medium, s: awaiting review

#530 App Cmd Refactor + Feature Creep
  discord/application_command.py
  docs/api.rst
  nextcord/application_command.py
  nextcord/client.py
  nextcord/enums.py
  nextcord/errors.py
  nextcord/ext/application_checks/core.py
  nextcord/ext/application_checks/errors.py
  nextcord/ext/commands/bot.py
  nextcord/ext/slash_utils/__init__.py
  nextcord/ext/slash_utils/slash.py
  nextcord/guild.py
  nextcord/http.py
  nextcord/interactions.py
  nextcord/member.py
  nextcord/scheduled_events.py
  nextcord/shard.py
  nextcord/state.py
  nextcord/types/interactions.py
  nextcord/utils.py
  nextcord/voice_client.py
Labels: t: enhancement, p: medium, s: awaiting review, 2.0
