Repository nextcord/nextcord, pull requests merged in 2022-02, with the labels that each got.

#356 Implement scheduled event covers
  nextcord/asset.py
  nextcord/guild.py
  nextcord/scheduled_events.py
  nextcord/types/scheduled_events.py
Labels: t: enhancement

#462 Change __title__ to nextcord
  discord/__init__.py
  nextcord/__init__.py
Labels: t: meta

#469 Task bugfix and refactoring
  nextcord/ext/tasks/__init__.py
Labels: t: bug, s: awaiting review

#471 fix subscription is so so so so low
  nextcord/channel.py
  nextcord/message.py
Labels: t: docs, s: awaiting review
