Repository nextcord/nextcord, pull requests merged in 2023-12, with the labels that each got.

#756 feat(app-cmds): get_application_command_from_signature improvements
  nextcord/client.py
  nextcord/state.py
Labels: t: enhancement, p: low, s: awaiting review

#1126 build: use poetry over pip+setuptools
  .coverage
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/publish.yml
  .gitignore
  .readthedocs.yml
  CONTRIBUTING.md
  docs/requirements.txt
  nextcord/__init__.py
  pyproject.toml
  requirements-dev.txt
  requirements.txt
  setup.py
Labels: p: medium, t: meta, s: awaiting review, 3.0

#1136 docs: move enum docs inline and add missing
  docs/api.rst
  nextcord/enums.py
Labels: t: docs, p: low

#989 feat(app-cmds): cog_command_error for application commands
  nextcord/application_command.py
  nextcord/client.py
Labels: t: enhancement, p: low

#1124 docs(permissions): add more info for forum channel permissions
  nextcord/permissions.py
Labels: t: docs, p: low, s: awaiting review, 3.0

#1068 docs(ui): specify what items modals support
  nextcord/ui/modal.py
Labels: t: docs, p: low, s: awaiting review
