Repository nextcord/nextcord, pull requests merged in 2023-01, with the labels that each got.

#916 docs(guild): add missing features
  nextcord/guild.py
  nextcord/types/guild.py
Labels: t: docs, p: low, s: awaiting review

#966 feat(role): update tags with recent fields
  nextcord/role.py
  nextcord/types/role.py
Labels: p: high, s: awaiting review, t: api coverage, 2.4

#965 refactor: use audit log `after` query param
  nextcord/http.py
  nextcord/iterators.py
Labels: p: medium, s: awaiting review, t: refactor, 2.4

#968 feat(state): add on_thread_create
  docs/api.rst
  nextcord/state.py
Labels: p: high, s: awaiting review, t: api coverage, 2.4

#834 feat: http ratelimit events
  docs/api.rst
  nextcord/client.py
  nextcord/http.py
Labels: t: enhancement, p: medium, s: awaiting review

#914 feat: add create_webhook in forum & voice channels
  nextcord/channel.py
Labels: t: enhancement, p: low, s: awaiting review

#905 refactor(abc): remove the use of ** for GuildChannel.move
  nextcord/abc.py
Labels: p: low, s: awaiting review, t: refactor

#932 feat(guild): add `invite_disabled` to `edit`
  nextcord/guild.py
Labels: p: high, s: awaiting review, t: api coverage, 2.4

#976 refactor: use pyright 1.1.190
  nextcord/components.py
  nextcord/ext/commands/core.py
  nextcord/ext/tasks/__init__.py
  nextcord/ui/modal.py
  requirements-dev.txt
Labels: p: low, s: awaiting review, t: refactor

#887 feat(automod): regex patterns
  nextcord/auto_moderation.py
  nextcord/types/auto_moderation.py
Labels: p: low, s: awaiting review, t: api coverage, 2.4

#980 refactor(app-cmds): use a metaclass for String and Range
  nextcord/application_command.py
Labels: p: low, t: refactor
