Repository nextcord/nextcord, pull requests merged in 2023-02, with the labels that each got.

#985 fix(iterators): import PartialUserPayload during runtime
  nextcord/iterators.py
Labels: t: bug, p: high

#964 feat: add role connections
  docs/api.rst
  nextcord/__init__.py
  nextcord/enums.py
  nextcord/http.py
  nextcord/role_connections.py
  nextcord/types/appinfo.py
  nextcord/types/role_connections.py
Labels: p: high, t: api coverage, 2.4

#969 feat(enums): add StickerFormatType.gif
  docs/api.rst
  nextcord/enums.py
Labels: p: medium, s: awaiting review, t: api coverage

#974 feat: add on_guild_audit_log_entry_create event
  nextcord/flags.py
  nextcord/state.py
Labels: p: medium, s: awaiting review, t: api coverage, 2.4

#987 docs(README): add missing nextcord import
  README.rst
Labels: t: docs, p: low, s: awaiting review

#942 feat(channel): add default forum layout
  docs/api.rst
  nextcord/abc.py
  nextcord/channel.py
  nextcord/enums.py
  nextcord/http.py
  nextcord/types/channel.py
Labels: p: medium, s: requested changes, t: api coverage, 2.4

#709 feat(app-cmds): support nsfw only commands
  nextcord/application_command.py
  nextcord/client.py
  nextcord/types/interactions.py
Labels: p: medium, t: api coverage, 2.4

#979 feat(message): send message flag
  nextcord/abc.py
  nextcord/channel.py
  nextcord/http.py
  nextcord/interactions.py
  nextcord/webhook/async_.py
Labels: p: high, s: awaiting review, t: api coverage, 2.4

#971 refactor(webhook): use WeakValueDictionary for _locks
  nextcord/webhook/async_.py
  nextcord/webhook/sync.py
Labels: p: medium, s: awaiting review, t: refactor

#959 refactor: remove mutable parameter defaults
  nextcord/application_command.py
  nextcord/http.py
Labels: t: bug, p: medium
