Repository nextcord/nextcord, pull requests merged in 2023-09, with the labels that each got.

#1017 feat: add text in stage
  docs/api.rst
  nextcord/abc.py
  nextcord/channel.py
  nextcord/enums.py
  nextcord/guild.py
  nextcord/message.py
  nextcord/types/guild.py
Labels: p: high, t: api coverage, 2.6

#1081 refactor(flags)!: remove `ApplicationFlags.active`
  nextcord/flags.py
Labels: p: low, s: awaiting review, t: removal, 2.6

#1099 feat(utils): add format_ts
  nextcord/utils.py
Labels: t: enhancement, p: low, s: awaiting review, 2.6

#1109 fix: make `state` fallback to `name` for CustomActivity
  nextcord/activity.py
Labels: t: bug, p: medium, s: awaiting review, 2.6

#1042 feat(flags): add MemberFlags and relevant fields
  docs/api.rst
  nextcord/flags.py
  nextcord/member.py
  nextcord/types/member.py
Labels: p: high, s: awaiting review, t: api coverage, 2.6

#1050 fix(iterators): allow querying over 100 audit log entries
  nextcord/iterators.py
Labels: t: bug, p: high, s: awaiting review

#1115 refactor: remove _modify_api_version
  nextcord/http.py
Labels: p: medium, s: awaiting review, t: removal
