Repository nextcord/nextcord, pull requests merged in 2023-08, with the labels that each got.

#1065 feat: see all permissions required to run a command
  nextcord/application_command.py
  nextcord/ext/application_checks/core.py
  nextcord/ext/commands/core.py
Labels: t: enhancement, p: low, s: awaiting review, 2.6

#1101 docs: Fix docstring in add_cog
  nextcord/ext/commands/bot.py
Labels: t: docs, p: low

#1046 fix(app-cmds): unfocused options not getting passed in autocomplete callback
  nextcord/application_command.py
Labels: t: bug, p: medium, s: awaiting review

#1105 fix(scheduled-events): event metadata missing
  nextcord/scheduled_events.py
Labels: t: bug, p: high, s: awaiting review

#1098 fix(threads): update applied_tag_ids
  nextcord/threads.py
Labels: t: bug, p: medium, s: awaiting review

#1086 docs: update `StickerType.standard`
  docs/api.rst
Labels: t: docs, p: low, s: awaiting review, s: waiting for discord, 2.6

#999 feat(raw-models): add guild and user attr to RawMemberRemoveEvent
  nextcord/raw_models.py
  nextcord/state.py
Labels: p: medium, s: awaiting review, t: api coverage, 2.6

#1106 fix(scheduled-events): sort out optionals and nullables
  nextcord/scheduled_events.py
  nextcord/types/scheduled_events.py
Labels: t: bug, p: critical, s: awaiting review

#1100 chore(examples): use `Locale` enum instead of strings
  examples/application_commands/localization.py
Labels: p: low, s: awaiting review

#1088 feat: add attachment flags
  nextcord/flags.py
  nextcord/message.py
  nextcord/types/message.py
Labels: p: medium, s: awaiting review, t: api coverage, 2.6

#1104 fix: menu assigning failing due to read only attributes
  nextcord/components.py
Labels: t: bug, p: high, s: awaiting review, 2.6

#1108 docs: fix build warnings
  nextcord/ui/select/mentionable.py
  nextcord/ui/select/user.py
Labels: t: docs, p: low, s: awaiting review

#1084 feat: add role flags
  docs/api.rst
  nextcord/flags.py
  nextcord/role.py
  nextcord/types/role.py
Labels: p: medium, s: awaiting review, t: api coverage, 2.6

#1093 feat(iterators): add `GuildIterator.with_counts`
  nextcord/client.py
  nextcord/http.py
  nextcord/iterators.py
Labels: p: medium, s: awaiting review, t: api coverage, 2.6

#1080 feat(auto_moderation): add join and mention raid fields
  nextcord/auto_moderation.py
  nextcord/guild.py
  nextcord/types/auto_moderation.py
  nextcord/types/guild.py
Labels: p: medium, s: awaiting review, t: api coverage, 2.6
