Repository nextcord/nextcord, pull requests merged in 2023-06, with the labels that each got.

#1051 fix(audit_logs)!: channel_id can be None due AutoMod blocking nickname changes
  nextcord/audit_logs.py
Labels: t: bug, p: high, s: awaiting review, t: refactor

#990 feat(flags): add missing MessageFlags values
  nextcord/flags.py
Labels: p: high, s: awaiting review, t: api coverage, 2.6

#1026 feat(flags): add ApplicationFlags.application_auto_moderation_rule_create
  nextcord/flags.py
Labels: p: medium, s: awaiting review, t: api coverage, 2.6

#1063 fix(guild): update guild limits to 25MiB default
  nextcord/guild.py
Labels: p: high, s: awaiting review, t: api coverage, 2.6

#1027 docs(abc): remove the position specification
  nextcord/abc.py
Labels: t: docs, p: medium, s: awaiting review

#886 feat(View): add prevent_update param
  nextcord/abc.py
  nextcord/interactions.py
  nextcord/message.py
  nextcord/ui/view.py
Labels: t: enhancement, p: low, s: awaiting review

#1067 feat(guild): add premium_progress_bar_enabled
  nextcord/guild.py
  nextcord/types/guild.py
Labels: p: high, s: awaiting review, t: api coverage, 2.6

#1048 refactor(app-cmds): move global checks to Client
  nextcord/application_command.py
  nextcord/client.py
  nextcord/ext/commands/bot.py
  nextcord/state.py
Labels: t: enhancement, p: medium, s: awaiting review

#1074 fix(guild): premium_progress_bar_enabled can be null
  nextcord/guild.py
  nextcord/types/guild.py
Labels: t: bug, p: high, s: awaiting review
