Repository nextcord/nextcord, pull requests merged in 2023-07, with the labels that each got.

#1033 feat: add guild preview
  docs/api.rst
  nextcord/__init__.py
  nextcord/client.py
  nextcord/emoji.py
  nextcord/guild_preview.py
  nextcord/http.py
  nextcord/types/guild.py
Labels: p: low, s: awaiting review, t: api coverage

#843 feat: track and expose non-persistent views
  nextcord/client.py
  nextcord/state.py
  nextcord/ui/view.py
Labels: t: enhancement, p: low, s: awaiting review

#1064 chore: remove redundant pr template checkboxes
  .github/PULL_REQUEST_TEMPLATE.md
Labels: p: low, t: meta, s: awaiting review

#1071 refactor: update to pyright 1.1.317
  docs/extensions/builder.py
  docs/requirements.txt
  nextcord/application_command.py
  nextcord/channel.py
  nextcord/client.py
  nextcord/components.py
  nextcord/emoji.py
  nextcord/enums.py
  nextcord/ext/commands/bot.py
  nextcord/ext/commands/converter.py
  nextcord/ext/commands/cooldowns.py
  nextcord/ext/commands/core.py
  nextcord/ext/commands/help.py
  nextcord/gateway.py
  nextcord/guild.py
  nextcord/http.py
  nextcord/invite.py
  nextcord/iterators.py
  nextcord/message.py
  nextcord/shard.py
  nextcord/state.py
  nextcord/template.py
  nextcord/types/channel.py
  nextcord/types/invite.py
  nextcord/ui/button.py
  nextcord/ui/select/string.py
  nextcord/ui/text_input.py
  nextcord/utils.py
  nextcord/voice_client.py
  nextcord/webhook/async_.py
  nextcord/webhook/sync.py
  pyproject.toml
  requirements-dev.txt
Labels: p: low, s: awaiting review, t: refactor

#1008 fix(app-cmds): incomplete payloads giving tracebacks within autocomplete
  nextcord/application_command.py
Labels: t: bug, p: medium, s: awaiting review

#1061 feat: implement new username system
  nextcord/abc.py
  nextcord/enums.py
  nextcord/member.py
  nextcord/types/user.py
  nextcord/user.py
  nextcord/webhook/async_.py
Labels: p: high, s: awaiting review, t: api coverage, 2.6

#1013 feat(guild): add default_forum_layout to create_forum_channel
  nextcord/guild.py
  nextcord/http.py
Labels: p: medium, s: awaiting review, t: api coverage

#1090 docs(README): update Discord API guild invite
  README.rst
Labels: t: docs, p: low, s: awaiting review

#1096 refactor(user): use key access for `BaseUser.discriminator`
  nextcord/user.py
Labels: p: low, s: awaiting review, t: refactor, 2.6
