Repository nextcord/nextcord, pull requests merged in 2023-04, with the labels that each got.

#1021 fix: ForumChannel and Thread returning wrong ForumTags
  nextcord/channel.py
  nextcord/threads.py
  nextcord/types/channel.py
Labels: t: bug, p: high, s: awaiting review

#1029 chore: prefer os.environ
  examples/secure_token_storage.py
Labels: p: low, t: meta, s: awaiting review

#1014 fix(state): hard crash when user_id is None
  nextcord/state.py
Labels: t: bug, p: high, s: awaiting review

#986 docs(app-cmds): document SlashCommandMixin.options
  nextcord/application_command.py
Labels: t: docs, p: low, s: awaiting review

#998 feat(file): add context manager to File
  nextcord/file.py
Labels: t: enhancement, p: low, s: awaiting review

#1041 docs(guild): fix typo of Optional
  nextcord/guild.py
Labels: t: docs

#1040 revert: "docs(app-cmds): document SlashCommandMixin.options"
  nextcord/application_command.py
Labels: t: bug, p: critical
