Repository nextcord/nextcord, pull requests merged in 2023-03, with the labels that each got.

#992 fix: Support Interaction annotation with client type specified
  nextcord/application_command.py
Labels: t: bug, p: medium, s: awaiting review

#1005 refactor(gateway): switch to 74 byte UDP packet format for IP discovery
  nextcord/gateway.py
Labels: p: high, s: awaiting review, t: api coverage

#1009 fix(voice): include ssrc parameter when sending a `SPEAKING` payload
  nextcord/gateway.py
Labels: t: bug, p: high, s: awaiting review

#1007 refactor(channel): add invitable argument in create_thread method
  nextcord/channel.py
Labels: p: high, t: api coverage, 2.5

#1006 fix(colour): use new dark theme colour
  nextcord/colour.py
Labels: t: bug, p: medium, s: awaiting review

#1020 typing(commands): resolve issues with command and group types
  nextcord/ext/commands/core.py
Labels: p: medium, s: awaiting review, t: typing

#1028 docs(readme): fix examples links
  README.rst
Labels: t: docs, p: high, s: awaiting review
