Repository nextcord/nextcord, pull requests merged in 2024-10, with the labels that each got.

#1004 fix(app-cmds): before and after invoke hooks not working for function inside cogs
  nextcord/application_command.py
Labels: t: bug, p: medium, s: awaiting review

#1190 feat(webhook): support to create posts via webhook
  nextcord/webhook/async_.py
  nextcord/webhook/sync.py
Labels: p: medium, s: awaiting review, t: api coverage

#1209 feat: add message snapshots/forwarding
  docs/api.rst
  nextcord/abc.py
  nextcord/enums.py
  nextcord/message.py
  nextcord/types/message.py
Labels: p: medium, s: awaiting review, t: api coverage, 3.0
