Repository nextcord/nextcord, pull requests merged in 2024-11, with the labels that each got.

#1219 refactor(client): future-proof event loop handling with get_event_loop
  nextcord/client.py
Labels: p: medium, s: awaiting review, t: refactor, 3.0

#1206 feat(guild): add `fetch_role`
  nextcord/guild.py
  nextcord/http.py
Labels: p: low, s: awaiting review, t: api coverage

#1172 feat(guild): add `bulk_ban` function
  docs/api.rst
  nextcord/bans.py
  nextcord/guild.py
  nextcord/http.py
  nextcord/types/guild.py
Labels: p: medium, s: awaiting review, t: api coverage

#1225 build(player): migrate to audioop-lts on Python >= 3.13
  pyproject.toml
Labels: p: high, t: meta, s: awaiting review, 3.0

#1224 ci(lint): Add Python 3.13 to lint version matrix
  .github/workflows/lint.yml
  pyproject.toml
Labels: p: medium, t: meta, 3.0

#1221 chore: Upgrade Sphinx to 6.2.0 to allow building on Python 3.13
  pyproject.toml
Labels: t: docs, s: stalled
