Repository nextcord/nextcord, pull requests merged in 2024-06, with the labels that each got.

#1135 chore: add 3.12 to supported lists
  .github/workflows/lint.yml
  pyproject.toml
Labels: p: medium, t: meta, s: awaiting review

#1129 removal!: deprecations from 2.0
  nextcord/application_command.py
  nextcord/client.py
  nextcord/embeds.py
  nextcord/guild.py
  nextcord/member.py
Labels: p: high, s: awaiting review, t: removal, 3.0

#1192 feat(auto_moderation): Add custom_message support
  nextcord/auto_moderation.py
  nextcord/types/auto_moderation.py
Labels: p: low, s: awaiting review, t: api coverage

#1183 feat(widget): update display_name method to include global_name
  nextcord/widget.py
Labels: t: enhancement, p: low, s: awaiting review

#1173 feat(invite): add `type` attribute
  nextcord/enums.py
  nextcord/invite.py
  nextcord/types/invite.py
Labels: p: low, s: awaiting review, t: api coverage

#1177 feat: add list of webhooks to forum, stage, and voice channels
  nextcord/channel.py
Labels: p: medium, s: awaiting review, t: api coverage

#1165 doc: add clarification to executable param
  nextcord/player.py
Labels: t: docs, p: low, s: awaiting review

#1194 docs(automod): fix typo of intents.message_content
  nextcord/auto_moderation.py
Labels: t: docs, p: low, s: awaiting review

#1188 docs(audit-logs): document missing attribute
  nextcord/audit_logs.py
Labels: t: docs, p: low, s: awaiting review
