Repository nextcord/nextcord, pull requests merged in 2024-12, with the labels that each got.

#1111 feat: add voice messages
  nextcord/flags.py
  nextcord/message.py
  nextcord/permissions.py
  nextcord/types/message.py
Labels: p: medium, s: awaiting review, t: api coverage

#1228 fix(client): remove duplication of views in views/all_views
  nextcord/ui/view.py
Labels: t: bug, p: high, s: awaiting review, 3.0

#1223 feat(permissions): update Permission classmethods
  nextcord/permissions.py
Labels: p: high, s: awaiting review, t: api coverage

#1207 feat(member): add guild banners
  nextcord/asset.py
  nextcord/member.py
  nextcord/types/member.py
Labels: p: low, s: awaiting review, t: api coverage

#1208 feat(utils): add `integration_type` to `oauth_url` helper
  nextcord/utils.py
Labels: p: low, s: awaiting review

#1234 build: set minimum python version to 3.12
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/publish.yml
  .readthedocs.yml
  README.rst
  docs/extensions/builder.py
  docs/intro.rst
  nextcord/role.py
  nextcord/state.py
  nextcord/utils.py
  pyproject.toml
Labels: p: medium, s: awaiting review, t: refactor, 3.0

#950 refactor!: rewrite async iterators
  docs/api.rst
  docs/conf.py
  nextcord/abc.py
  nextcord/channel.py
  nextcord/client.py
  nextcord/guild.py
  nextcord/iterators.py
  nextcord/reaction.py
  nextcord/scheduled_events.py
Labels: p: low, s: awaiting review, t: refactor, 3.0
