Repository nextcord/nextcord, pull requests merged in 2024-09, with the labels that each got.

#1181 feat(app-cmds): Implement User-Installed Apps
  docs/api.rst
  examples/application_commands/user_installed_command.py
  nextcord/appinfo.py
  nextcord/application_command.py
  nextcord/client.py
  nextcord/enums.py
  nextcord/interactions.py
  nextcord/message.py
  nextcord/types/appinfo.py
  nextcord/types/interactions.py
  nextcord/types/message.py
Labels: p: medium, s: awaiting review, t: api coverage

#1160 feat(webhooks): allow editing webhook messages that were sent in threads
  nextcord/webhook/async_.py
  nextcord/webhook/sync.py
Labels: p: low, s: awaiting review, t: api coverage

#917 refactor: move listeners to the main library
  nextcord/client.py
  nextcord/ext/commands/bot.py
Labels: s: in progress, p: low, t: refactor, 3.0

#1044 docs(app-cmds): document SlashCommandMixin.options
  nextcord/application_command.py
Labels: t: docs, p: low, s: awaiting review

#1132 feat: add missing fields for stage instance
  nextcord/channel.py
  nextcord/http.py
  nextcord/stage_instance.py
  nextcord/types/channel.py
Labels: p: medium, s: awaiting review, t: api coverage
