Repository nextcord/nextcord, pull requests merged in 2024-05, with the labels that each got.

#1057 refactor: HTTPClient Re-Core
  docs/api.rst
  nextcord/client.py
  nextcord/errors.py
  nextcord/gateway.py
  nextcord/http.py
  nextcord/webhook/async_.py
Labels: s: in progress, p: low, t: refactor, 3.0

#1180 fix(DiscordWebSocket): Raise WebSocketClosure on protocol level errors
  nextcord/gateway.py
Labels: t: bug, p: low

#1171 feat(user): add `banner` param to ClientUser.edit
  nextcord/user.py
Labels: p: low, s: awaiting review, t: api coverage

#1186 refactor: remove _InteractionMessageState hack
  nextcord/interactions.py
Labels: t: bug, p: medium, s: awaiting review, t: refactor
