Repository nextcord/nextcord, pull requests merged in 2025-04, with the labels that each got.

#1251 fix: specify correct types for Opus on Apple Silicon
  nextcord/opus.py
Labels: t: bug, p: medium, s: awaiting review

#1250 fix(gateway): handle improper 1000 closures by Discord
  nextcord/gateway.py
Labels: t: bug, p: medium, s: awaiting review

#1237 fix(user): use correct condition for default_avatar index
  nextcord/user.py
Labels: t: bug, p: high, s: awaiting review

#1252 fix(components): prevent UnboundLocalError with missing emoji in SelectOptionPayload
  nextcord/components.py
Labels: t: bug, p: high, s: awaiting review

#940 feat: role subscriptions
  nextcord/enums.py
  nextcord/flags.py
  nextcord/guild.py
  nextcord/message.py
  nextcord/role.py
  nextcord/types/guild.py
  nextcord/types/integration.py
  nextcord/types/message.py
Labels: p: high, s: awaiting review, t: api coverage
